openapi: 3.0.0
info:
  title: chat application API
  description: This is backend api for chat application.
  version: 0.0.1

servers:
  - url: http://localhost:4000/{version}
    variables:
      version:
        default: " "
        enum:
          - v1
          - " "
    description: 

paths:
  /:
    get:
      summary: Sample route for welcome message
      description: Json response welcome message.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      message: 
                        type: string
                  message:
                    type: string
                  error:
                    type: string